package pe.controlfinanciero.app;

import android.app.*;
import android.os.Bundle;
import android.content.*;
import android.database.Cursor;
import android.database.sqlite.*;
import android.graphics.Color;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;
import java.time.*;
import java.time.temporal.TemporalAdjusters;
import java.util.*;

public class MainActivity extends Activity {
    static final String[] TYPES={"Ingreso","Gasto","Ahorro","Retiro ahorro","Pago deuda","Préstamo recibido","Dinero prestado","Cobro"};
    static final String[] CATS={"Vivienda","Alimentación","Moto/Transporte","Servicios","Hogar","Salud","Educación/Profesión","Personal/Ocio","Viajes","Imprevistos/Otros","Deudas","Ahorro/Metas"};
    static final String[] CLS={"Necesidad","Deseo","Deuda","Ahorro","Ingreso"};
    static final String[] NAT={"Fijo","Variable","Eventual"};
    static final String[] MED={"Yape","Efectivo","Transferencia","Tarjeta","Plin","Otro"};
    final int BG=Color.rgb(9,12,16), CARD=Color.rgb(22,27,34), TEXT=Color.rgb(241,245,249), MUTED=Color.rgb(160,174,192), BLUE=Color.rgb(100,181,246), GREEN=Color.rgb(102,187,106), RED=Color.rgb(239,83,80), AMBER=Color.rgb(255,183,77);
    DB db; SharedPreferences sp; FrameLayout body; String pendingExport="";
    @Override public void onCreate(Bundle b){super.onCreate(b);db=new DB(this);sp=getSharedPreferences("cfg",MODE_PRIVATE);seed();setContentView(shell());dashboard();}
    void seed(){if(!sp.contains("income"))sp.edit().putString("income","2000").putString("opening","0").putString("minimum","0").putString("saveRate","0.20").apply();}
    View shell(){LinearLayout r=vbox(0);r.setBackgroundColor(BG);LinearLayout h=vbox(14);h.addView(txt("Control Financiero",24,TEXT,true));h.addView(txt("Registro diario • límites • exportación a Excel",12,MUTED,false));r.addView(h);body=new FrameLayout(this);r.addView(body,new LinearLayout.LayoutParams(-1,0,1));LinearLayout n=new LinearLayout(this);n.setOrientation(LinearLayout.HORIZONTAL);for(String s:new String[]{"Inicio","Registrar","Movs","Pagos","Ajustes"}){Button x=btn(s);n.addView(x,new LinearLayout.LayoutParams(0,52,1));}((Button)n.getChildAt(0)).setOnClickListener(v->dashboard());((Button)n.getChildAt(1)).setOnClickListener(v->movementForm(null));((Button)n.getChildAt(2)).setOnClickListener(v->movements());((Button)n.getChildAt(3)).setOnClickListener(v->payments());((Button)n.getChildAt(4)).setOnClickListener(v->settings());r.addView(n);return r;}
    void dashboard(){body.removeAllViews();ScrollView sv=new ScrollView(this);LinearLayout b=vbox(14);Snap s=snapshot();b.addView(title("Resumen de "+YearMonth.now()));b.addView(card(s.verdict,s.endProjection<0?RED:GREEN,true));LinearLayout a=row();a.addView(kpi("Saldo visible",s.visible,BLUE),wt());a.addView(kpi("Gastable",s.spendable,GREEN),wt());b.addView(a);LinearLayout c=row();c.addView(kpi("Límite diario",s.daily,AMBER),wt());c.addView(kpi("Límite semanal",s.weekly,AMBER),wt());b.addView(c);b.addView(block("¿Me alcanza?",s.advice));b.addView(block("Compromisos","Pagos mensuales pendientes: S/ "+m(s.pending)+"
Ahorro objetivo pendiente: S/ "+m(s.savePending)+"
Saldo mínimo intocable: S/ "+m(s.minimum)));b.addView(block("Mes actual","Ingresos: S/ "+m(s.income)+"
Gastos: S/ "+m(s.expenses)+"
Ahorro: S/ "+m(s.savings)+"
Pago de deuda: S/ "+m(s.debt)+"
Préstamos recibidos: S/ "+m(s.loans)));Button ev=primary("EVALUARME");ev.setOnClickListener(v->new AlertDialog.Builder(this).setTitle(s.verdict).setMessage(s.advice+"

Proyección de cierre: S/ "+m(s.endProjection)+"
Días restantes: "+s.days).setPositiveButton("Entendido",null).show());b.addView(ev);Button ex=btn("COPIAR ESTA SEMANA PARA EXCEL");ex.setOnClickListener(v->copyWeek());b.addView(ex);Button csv=btn("EXPORTAR ESTA SEMANA A CSV");csv.setOnClickListener(v->exportWeek());b.addView(csv);sv.addView(b);body.addView(sv);}
    void movementForm(Long editId){body.removeAllViews();ScrollView sv=new ScrollView(this);LinearLayout b=vbox(14);b.addView(title(editId==null?"Registrar movimiento":"Editar movimiento"));Rec old=editId==null?null:db.one(editId);EditText date=input("Fecha AAAA-MM-DD",old==null?LocalDate.now().toString():old.date);Spinner type=spin(TYPES,old==null?"Gasto":old.type),cat=spin(CATS,old==null?"Alimentación":old.cat),cl=spin(CLS,old==null?"Necesidad":old.cls),nat=spin(NAT,old==null?"Variable":old.nat),med=spin(MED,old==null?"Yape":old.med);EditText concept=input("Concepto",old==null?"":old.concept),amount=num("Monto (S/)",old==null?"":m(old.amount)),dest=input("Destino / persona / meta",old==null?"":old.dest),note=input("Nota",old==null?"":old.note);for(View v:new View[]{label("Fecha"),date,label("Tipo"),type,label("Categoría"),cat,concept,amount,label("Clasificación"),cl,label("Naturaleza"),nat,label("Medio"),med,dest,note})b.addView(v);Button save=primary("GUARDAR MOVIMIENTO");save.setOnClickListener(v->{try{double val=Double.parseDouble(amount.getText().toString().replace(",","."));if(val<=0)throw new Exception();LocalDate.parse(date.getText().toString());Rec r=new Rec();r.id=editId==null?0:editId;r.date=date.getText().toString();r.type=type.getSelectedItem().toString();r.cat=cat.getSelectedItem().toString();r.concept=concept.getText().toString().trim();r.amount=val;r.cls=cl.getSelectedItem().toString();r.nat=nat.getSelectedItem().toString();r.med=med.getSelectedItem().toString();r.dest=dest.getText().toString().trim();r.month=r.date.substring(0,7);r.note=note.getText().toString().trim();if(r.concept.isEmpty()){toast("Escribe un concepto");return;}if(editId==null)db.add(r);else db.update(r);toast("Guardado");dashboard();}catch(Exception e){toast("Revisa fecha y monto");}});b.addView(save);sv.addView(b);body.addView(sv);}
    void movements(){body.removeAllViews();ScrollView sv=new ScrollView(this);LinearLayout b=vbox(12);b.addView(title("Movimientos"));List<Rec> list=db.range(LocalDate.now().minusDays(60).toString(),LocalDate.now().toString());if(list.isEmpty())b.addView(block("Sin datos","Aún no has registrado movimientos."));for(Rec r:list){TextView x=card(r.date+" • "+r.type+"
"+r.concept+" — S/ "+m(r.amount)+"
"+r.cat+" • "+r.med,14,TEXT,false);x.setOnClickListener(v->new AlertDialog.Builder(this).setTitle(r.concept).setItems(new String[]{"Editar","Eliminar","Cancelar"},(d,w)->{if(w==0)movementForm(r.id);if(w==1)new AlertDialog.Builder(this).setMessage("¿Eliminar este movimiento?").setPositiveButton("Eliminar",(dd,ww)->{db.del(r.id);movements();}).setNegativeButton("Cancelar",null).show();}).show());b.addView(x);}sv.addView(b);body.addView(sv);}
    void payments(){body.removeAllViews();ScrollView sv=new ScrollView(this);LinearLayout b=vbox(12);b.addView(title("Pagos mensuales"));b.addView(txt("Registra alquiler, celular, internet, cuotas u otros compromisos que se repiten cada mes.",13,MUTED,false));Button add=primary("+ AGREGAR PAGO MENSUAL");add.setOnClickListener(v->paymentDialog());b.addView(add);for(Pay p:db.pays()){YearMonth ym=YearMonth.now();double paid=db.sumExact(p.type,p.concept,ym.atDay(1).toString(),ym.atEndOfMonth().toString());double pen=Math.max(0,p.amount-paid);String st=pen<=0?"PAGADO":(p.day<LocalDate.now().getDayOfMonth()?"VENCIDO":"PENDIENTE");TextView x=card(p.concept+" — S/ "+m(p.amount)+"
Día "+p.day+" • "+p.type+" • "+st+(pen>0?"
Pendiente: S/ "+m(pen):""),14,pen<=0?GREEN:(st.equals("VENCIDO")?RED:TEXT),false);x.setOnLongClickListener(v->{new AlertDialog.Builder(this).setMessage("¿Eliminar "+p.concept+"?").setPositiveButton("Eliminar",(d,w)->{db.delPay(p.id);payments();}).setNegativeButton("Cancelar",null).show();return true;});b.addView(x);}sv.addView(b);body.addView(sv);}
    void paymentDialog(){LinearLayout b=vbox(12);EditText con=input("Concepto exacto","");EditText amt=num("Monto mensual","");EditText day=num("Día de pago (1-31)","1");Spinner typ=spin(new String[]{"Gasto","Pago deuda"},"Gasto");Spinner cat=spin(CATS,"Servicios");b.addView(con);b.addView(amt);b.addView(day);b.addView(label("Tipo"));b.addView(typ);b.addView(label("Categoría"));b.addView(cat);new AlertDialog.Builder(this).setTitle("Nuevo pago mensual").setView(b).setPositiveButton("Guardar",(d,w)->{try{Pay p=new Pay();p.concept=con.getText().toString().trim();p.amount=Double.parseDouble(amt.getText().toString().replace(",","."));p.day=Math.max(1,Math.min(31,Integer.parseInt(day.getText().toString())));p.type=typ.getSelectedItem().toString();p.cat=cat.getSelectedItem().toString();if(p.concept.isEmpty()||p.amount<=0)throw new Exception();db.addPay(p);payments();}catch(Exception e){toast("Datos inválidos");}}).setNegativeButton("Cancelar",null).show();}
    void settings(){body.removeAllViews();ScrollView sv=new ScrollView(this);LinearLayout b=vbox(14);b.addView(title("Ajustes financieros"));EditText income=num("Ingreso mensual esperado",sp.getString("income","2000")),opening=num("Saldo libre al inicio del mes",sp.getString("opening","0")),minimum=num("Saldo mínimo intocable",sp.getString("minimum","0")),rate=num("Ahorro objetivo (ej. 0.20 = 20%)",sp.getString("saveRate","0.20"));b.addView(income);b.addView(opening);b.addView(minimum);b.addView(rate);Button save=primary("GUARDAR AJUSTES");save.setOnClickListener(v->{try{double rr=Double.parseDouble(rate.getText().toString().replace(",","."));if(rr<0||rr>0.8)throw new Exception();sp.edit().putString("income",income.getText().toString()).putString("opening",opening.getText().toString()).putString("minimum",minimum.getText().toString()).putString("saveRate",rate.getText().toString()).apply();toast("Ajustes guardados");dashboard();}catch(Exception e){toast("Revisa los valores");}});b.addView(save);b.addView(block("Cómo interpreta tu dinero","Saldo visible = saldo inicial + entradas - salidas.
Gastable = lo que queda después de reservar pagos mensuales, ahorro objetivo y saldo intocable.
El límite diario y semanal se recalcula según los días que faltan del mes."));sv.addView(b);body.addView(sv);}
    Snap snapshot(){LocalDate now=LocalDate.now();YearMonth ym=YearMonth.from(now);String a=ym.atDay(1).toString(),z=ym.atEndOfMonth().toString();Snap s=new Snap();s.expected=d(sp.getString("income","2000"));s.opening=d(sp.getString("opening","0"));s.minimum=d(sp.getString("minimum","0"));double rate=d(sp.getString("saveRate","0.20"));s.income=db.sum("Ingreso",a,z);s.expenses=db.sum("Gasto",a,z);s.savings=db.sum("Ahorro",a,z);s.debt=db.sum("Pago deuda",a,z);s.loans=db.sum("Préstamo recibido",a,z);s.collections=db.sum("Cobro",a,z);s.withdraw=db.sum("Retiro ahorro",a,z);s.lent=db.sum("Dinero prestado",a,z);s.visible=s.opening+s.income+s.collections+s.loans+s.withdraw-s.expenses-s.savings-s.debt-s.lent;for(Pay p:db.pays())s.pending+=Math.max(0,p.amount-db.sumExact(p.type,p.concept,a,z));double basis=Math.max(s.expected,s.income);s.savePending=Math.max(0,basis*rate-s.savings);double sustainable=s.opening+basis+s.collections+s.withdraw-s.expenses-s.debt-s.lent-s.pending-s.savePending-s.minimum;s.endProjection=sustainable;s.spendable=Math.max(0,sustainable);s.days=Math.max(1,ym.lengthOfMonth()-now.getDayOfMonth()+1);s.daily=s.spendable/s.days;s.weekly=Math.min(s.spendable,s.daily*7);if(s.endProjection<0){s.verdict="NO ALCANZA CON EL PLAN ACTUAL";s.advice="Te faltan aproximadamente S/ "+m(-s.endProjection)+" para cerrar el mes respetando tus pagos, ahorro y saldo mínimo. Prioriza vivienda, alimentación, transporte de trabajo, salud y deudas; reduce primero ocio, compras postergables y viajes.";}else if(s.spendable<100){s.verdict="ALCANZA, PERO ESTÁS MUY AJUSTADO";s.advice="Tu margen libre es pequeño. Usa como techo S/ "+m(s.daily)+" por día y evita gastos no esenciales hasta asegurar los pagos del mes.";}else{s.verdict="VAS EN UN RANGO SOSTENIBLE";s.advice="Puedes usar como techo aproximado S/ "+m(s.daily)+" por día o S/ "+m(s.weekly)+" por semana. Este límite ya reserva tus pagos, tu ahorro objetivo y tu saldo intocable.";}if(s.loans>0)s.advice+="

Importante: los préstamos recibidos no se consideran ingreso sostenible.";return s;}
    void copyWeek(){LocalDate now=LocalDate.now(),mon=now.with(TemporalAdjusters.previousOrSame(DayOfWeek.MONDAY)),sun=mon.plusDays(6);String t=exportText(db.range(mon.toString(),sun.toString()),"	");((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("Excel",t));toast("Semana copiada. Pégala en Excel desde la primera celda.");}
    void exportWeek(){LocalDate now=LocalDate.now(),mon=now.with(TemporalAdjusters.previousOrSame(DayOfWeek.MONDAY)),sun=mon.plusDays(6);pendingExport=exportText(db.range(mon.toString(),sun.toString()),",");Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("text/csv");i.putExtra(Intent.EXTRA_TITLE,"movimientos_"+mon+"_a_"+sun+".csv");startActivityForResult(i,10);}
    @Override protected void onActivityResult(int req,int res,Intent data){super.onActivityResult(req,res,data);if(req==10&&res==RESULT_OK&&data!=null){try(OutputStream o=getContentResolver().openOutputStream(data.getData())){o.write("﻿".getBytes(StandardCharsets.UTF_8));o.write(pendingExport.getBytes(StandardCharsets.UTF_8));toast("CSV exportado");}catch(Exception e){toast("No se pudo exportar");}}}
    String exportText(List<Rec> l,String sep){StringBuilder q=new StringBuilder();q.append(join(sep,"Fecha","Tipo","Categoría","Concepto","Monto (S/)","Clasificación","Naturaleza","Medio","Destino / persona / meta","Mes","Nota")).append("
");for(Rec r:l)q.append(join(sep,r.date,r.type,r.cat,r.concept,m(r.amount),r.cls,r.nat,r.med,r.dest,r.month,r.note)).append("
");return q.toString();}
    String join(String sep,String...v){StringBuilder b=new StringBuilder();for(int i=0;i<v.length;i++){if(i>0)b.append(sep);String x=v[i]==null?"":v[i];if(sep.equals(",")){x=x.replace(""","""");if(x.contains(",")||x.contains("
")||x.contains(""") )x="""+x+""";}else x=x.replace("	"," ").replace("
"," ");b.append(x);}return b.toString();}
    static class Rec{long id;String date,type,cat,concept,cls,nat,med,dest,month,note;double amount;}
    static class Pay{long id;String type,concept,cat;double amount;int day;}
    static class Snap{double expected,opening,minimum,income,expenses,savings,debt,loans,collections,withdraw,lent,visible,pending,savePending,endProjection,spendable,daily,weekly;int days;String verdict,advice;}
    static class DB extends SQLiteOpenHelper{DB(Context c){super(c,"finance.db",null,1);}public void onCreate(SQLiteDatabase d){d.execSQL("CREATE TABLE mov(id INTEGER PRIMARY KEY AUTOINCREMENT,date TEXT,type TEXT,cat TEXT,concept TEXT,amount REAL,cls TEXT,nat TEXT,med TEXT,dest TEXT,month TEXT,note TEXT)");d.execSQL("CREATE TABLE pay(id INTEGER PRIMARY KEY AUTOINCREMENT,type TEXT,concept TEXT,cat TEXT,amount REAL,day INTEGER)");}public void onUpgrade(SQLiteDatabase d,int a,int b){}
        void add(Rec r){getWritableDatabase().insert("mov",null,cv(r));}void update(Rec r){getWritableDatabase().update("mov",cv(r),"id=?",new String[]{""+r.id});}void del(long id){getWritableDatabase().delete("mov","id=?",new String[]{""+id});}
        ContentValues cv(Rec r){ContentValues c=new ContentValues();c.put("date",r.date);c.put("type",r.type);c.put("cat",r.cat);c.put("concept",r.concept);c.put("amount",r.amount);c.put("cls",r.cls);c.put("nat",r.nat);c.put("med",r.med);c.put("dest",r.dest);c.put("month",r.month);c.put("note",r.note);return c;}
        Rec one(long id){Cursor c=getReadableDatabase().rawQuery("SELECT * FROM mov WHERE id=?",new String[]{""+id});Rec r=c.moveToFirst()?rec(c):null;c.close();return r;}
        List<Rec> range(String a,String z){ArrayList<Rec> l=new ArrayList<>();Cursor c=getReadableDatabase().rawQuery("SELECT * FROM mov WHERE date BETWEEN ? AND ? ORDER BY date DESC,id DESC",new String[]{a,z});while(c.moveToNext())l.add(rec(c));c.close();return l;}
        Rec rec(Cursor c){Rec r=new Rec();r.id=c.getLong(c.getColumnIndexOrThrow("id"));r.date=c.getString(c.getColumnIndexOrThrow("date"));r.type=c.getString(c.getColumnIndexOrThrow("type"));r.cat=c.getString(c.getColumnIndexOrThrow("cat"));r.concept=c.getString(c.getColumnIndexOrThrow("concept"));r.amount=c.getDouble(c.getColumnIndexOrThrow("amount"));r.cls=c.getString(c.getColumnIndexOrThrow("cls"));r.nat=c.getString(c.getColumnIndexOrThrow("nat"));r.med=c.getString(c.getColumnIndexOrThrow("med"));r.dest=c.getString(c.getColumnIndexOrThrow("dest"));r.month=c.getString(c.getColumnIndexOrThrow("month"));r.note=c.getString(c.getColumnIndexOrThrow("note"));return r;}
        double sum(String t,String a,String z){Cursor c=getReadableDatabase().rawQuery("SELECT COALESCE(SUM(amount),0) FROM mov WHERE type=? AND date BETWEEN ? AND ?",new String[]{t,a,z});c.moveToFirst();double x=c.getDouble(0);c.close();return x;}double sumExact(String t,String con,String a,String z){Cursor c=getReadableDatabase().rawQuery("SELECT COALESCE(SUM(amount),0) FROM mov WHERE type=? AND concept=? AND date BETWEEN ? AND ?",new String[]{t,con,a,z});c.moveToFirst();double x=c.getDouble(0);c.close();return x;}
        void addPay(Pay p){ContentValues c=new ContentValues();c.put("type",p.type);c.put("concept",p.concept);c.put("cat",p.cat);c.put("amount",p.amount);c.put("day",p.day);getWritableDatabase().insert("pay",null,c);}void delPay(long id){getWritableDatabase().delete("pay","id=?",new String[]{""+id});}List<Pay> pays(){ArrayList<Pay> l=new ArrayList<>();Cursor c=getReadableDatabase().rawQuery("SELECT * FROM pay ORDER BY day,concept",null);while(c.moveToNext()){Pay p=new Pay();p.id=c.getLong(0);p.type=c.getString(1);p.concept=c.getString(2);p.cat=c.getString(3);p.amount=c.getDouble(4);p.day=c.getInt(5);l.add(p);}c.close();return l;}}
    LinearLayout vbox(int p){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(dp(p),dp(p),dp(p),dp(p));return x;}LinearLayout row(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.HORIZONTAL);return x;}LinearLayout.LayoutParams wt(){return new LinearLayout.LayoutParams(0,-2,1);}
    TextView txt(String s,int z,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);if(bold)t.setTypeface(null,1);t.setPadding(dp(10),dp(8),dp(10),dp(8));return t;}TextView title(String s){return txt(s,22,TEXT,true);}TextView label(String s){return txt(s,12,MUTED,false);}TextView card(String s,int z,int c,boolean bold){TextView t=txt(s,z,c,bold);t.setBackgroundColor(CARD);t.setPadding(dp(14),dp(14),dp(14),dp(14));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(6),0,dp(6));t.setLayoutParams(p);return t;}TextView block(String h,String s){return card(h+"
"+s,14,TEXT,false);}TextView kpi(String h,double x,int c){return card(h+"
S/ "+m(x),14,c,true);}Button btn(String s){Button b=new Button(this);b.setText(s);return b;}Button primary(String s){Button b=btn(s);b.setTextColor(Color.WHITE);b.setBackgroundColor(Color.rgb(25,118,210));return b;}EditText input(String hint,String val){EditText e=new EditText(this);e.setHint(hint);e.setText(val);e.setTextColor(TEXT);e.setHintTextColor(MUTED);e.setSingleLine(false);return e;}EditText num(String h,String v){EditText e=input(h,v);e.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);return e;}Spinner spin(String[] a,String selected){Spinner s=new Spinner(this);ArrayAdapter<String> ad=new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,a);s.setAdapter(ad);for(int i=0;i<a.length;i++)if(a[i].equals(selected)){s.setSelection(i);break;}return s;}void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}int dp(int v){return (int)(v*getResources().getDisplayMetrics().density+.5f);}double d(String x){try{return Double.parseDouble(x.replace(",","."));}catch(Exception e){return 0;}}static String m(double x){return String.format(Locale.US,"%.2f",x);}
}
